# Generated by Django 3.1.7 on 2021-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='department_pictures'),
        ),
    ]
