# Generated by Django 3.1.4 on 2021-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210619_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-pk'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='isBuh',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='это бухгалтер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isChef',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='это шеф'),
        ),
    ]
