# Generated by Django 3.1.4 on 2021-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210701_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='archive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архив'),
        ),
    ]
