# Generated by Django 3.1.4 on 2021-07-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenote',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to='app.Tags'),
        ),
    ]
