# Generated by Django 3.1.4 on 2021-05-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
