# Generated by Django 3.1.4 on 2021-08-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210805_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confidentially',
            field=models.BooleanField(default=False, verbose_name='Конфиденциально'),
        ),
    ]
