# Generated by Django 3.1.4 on 2021-08-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_confidentially'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confidentially',
        ),
        migrations.AddField(
            model_name='servicenote',
            name='confidentially',
            field=models.BooleanField(default=False, verbose_name='Конфиденциально'),
        ),
    ]
