# Generated by Django 3.1.7 on 2021-05-25 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20210524_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Подписать'), ('edit', 'На редактирование'), ('error', 'Отказать')], max_length=200, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.servicenote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписывающий',
                'verbose_name_plural': 'Подписывающие',
            },
        ),
    ]
