# Generated by Django 3.1.4 on 2021-08-12 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20210805_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenotetypes',
            name='users',
        ),
        migrations.AddField(
            model_name='servicenotetypes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to=settings.AUTH_USER_MODEL),
        ),
    ]
