# Generated by Django 3.1.4 on 2021-05-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_servicenote_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenote',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
