# Generated by Django 3.1.4 on 2021-08-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210812_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicenote',
            old_name='сurrency',
            new_name='currency',
        ),
    ]
