# Generated by Django 3.1.4 on 2021-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210812_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название валюты'),
        ),
    ]
