# Generated by Django 3.1.4 on 2021-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210526_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenote',
            name='fast',
            field=models.BooleanField(default=False),
        ),
    ]
