# Generated by Django 3.1.4 on 2021-05-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_servicenote_fast'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='user_signatures'),
        ),
    ]
