# Generated by Django 3.1.4 on 2021-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210813_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='buhstatus',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='buhstatus',
            name='status',
            field=models.CharField(choices=[('Одобрено', 'Одобрено'), ('На редактирование', 'На редактирование'), ('Отказано', 'Отказано')], default='success', max_length=256),
        ),
    ]
