# Generated by Django 3.1.4 on 2021-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210813_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buhstatus',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарии'),
        ),
    ]
