# Generated by Django 3.1.4 on 2021-05-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenote',
            name='signers',
        ),
    ]
