# Generated by Django 3.1.4 on 2021-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210813_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='buhstatus',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='buhstatus',
            name='status',
            field=models.CharField(choices=[('Одобрено', 'Одобрено'), ('На редактирование', 'На редактирование'), ('Отказано', 'Отказано')], default='Одобрено', max_length=256),
        ),
    ]
