# Generated by Django 3.1.4 on 2021-05-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_servicenote_signers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenote',
            name='user_index',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
