# Generated by Django 3.1.7 on 2021-05-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_servicenote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteusers',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
