# Generated by Django 3.1.4 on 2021-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_servicenotetypes_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenote',
            name='currency_text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
