# Generated by Django 3.1.7 on 2021-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_profile_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteusers',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteusers',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
