# Generated by Django 3.1.4 on 2021-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_profile_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteusers',
            options={'ordering': ['index'], 'verbose_name': 'Подписывающий', 'verbose_name_plural': 'Подписывающие'},
        ),
        migrations.AddField(
            model_name='servicenote',
            name='isChef',
            field=models.BooleanField(default=False),
        ),
    ]
