# Generated by Django 3.1.4 on 2021-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210617_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isChef',
            field=models.BooleanField(default=False),
        ),
    ]
