# Generated by Django 3.1.4 on 2021-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_profile_ischef'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isBuh',
            field=models.BooleanField(default=False),
        ),
    ]
