# Generated by Django 3.1.7 on 2021-06-19 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0029_auto_20210618_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenote',
            name='buh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='isBuh',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='isChef',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
